apiVersion: v1
kind: Service
metadata:
  name: wc-app-service
  labels:
    app: wc-app
spec:
  selector:
    app: wc-app
  ports:
  - protocol: TCP
    port: 4499
    targetPort: 4499
  type: LoadBalancer
